# Configuration GitHub Pages
title: "EDILPA - Église de Dieu Liberté par la Parole"
description: "Église de Dieu Liberté par la Parole INC. - Fondée en 1997 à Santo Domingo - Siège à Mombin Crochu, Haïti"
url: "https://jean15821.github.io"
baseurl: "/eglise-edilpa"
theme: null
